---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs.fullname" . }}-orm-config
  namespace: {{ include "nodejs.namespace" . }}
  labels:
     {{- include "nodejs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  ormconfig.env: {{ .Values.ormconfig | toYaml | b64enc | quote }}
