---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "nodejs.fullname" . }}-secret
  namespace: {{ include "nodejs.namespace" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
