apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs.fullname" . }}
  namespace: {{ include "nodejs.namespace" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodejs.service.type }}
  selector:
    {{- include "nodejs.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.nodejs.service.protocol }}
      port: {{ .Values.nodejs.containerPort }}
      targetPort: {{ .Values.nodejs.service.targetPort }}

