---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs.fullname" . }}-config
  namespace: {{ include "nodejs.namespace" . }}
  labels:
     {{- include "nodejs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
